apiVersion: apps/v1
kind: Deployment
metadata:
  name: fms-cert-expiry
spec:
  replicas: 1
  selector:
    matchLabels:
      name: fms-cert-expiry
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: fms-cert-expiry
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
      - name: fms-cert-expiry-volume
        persistentVolumeClaim:
          claimName: fms-cert-expiry-volume
      containers:
      - name: fms-cert-expiry
        image: quay.io/ukhomeofficedigital/fms_cert-expiry:{{ .DRONE_COMMIT_SHA }}
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: fms-cert-expiry
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: fms-cert-expiry
                key: AWS_SECRET_ACCESS_KEY
          - name: BUCKET
            valueFrom:
              secretKeyRef:
                name: fms-cert-expiry
                key: BUCKET
          - name: FMS_CERT_EXPIRY_PORT
            value: "443"
        volumeMounts:
        - name: fms-cert-expiry-volume
          mountPath: /home/ssl_expire_script
